# Generated by Django 2.1.15 on 2020-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, help_text='The detailed description of your post (will be shown on map)', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_membership',
            field=models.CharField(choices=[('0', 'I want to help'), ('1', 'I need help'), ('2', 'Inactive (invisible to others)')], default=2, help_text='Do you want or need help? Or you can set your status to inactive.', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='map_show_location',
            field=models.CharField(choices=[('0', 'rough'), ('1', 'exact')], default=0, help_text='if you choose exact - your location will be shown exactly; if you do not want to expose your exact location choose rough', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slogan',
            field=models.CharField(blank=True, help_text='The headline of your post (will be shown on map)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, help_text='Add your street for exact location', max_length=100),
        ),
    ]
