# Generated by Django 2.1.15 on 2020-04-02 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200329_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, help_text='The detailed description of your post (will be shown on map)', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9, !.?]*$', 'allowed are characters, numbers, points, question and exclamation mark')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slogan',
            field=models.CharField(blank=True, help_text='The headline of your post (will be shown on map)', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9, !.?]*$', 'allowed are characters, numbers, points, question and exclamation mark')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, help_text='Add your street and number for exact location (leave it out if you feel uncomfortable with it)', max_length=500),
        ),
    ]
