# Generated by Django 2.1.15 on 2020-04-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200402_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='help_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
