# Generated by Django 3.0.3 on 2020-03-13 20:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200313_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 20, 14, 29, 459347, tzinfo=utc), verbose_name='date of creation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slogan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 20, 14, 29, 459347, tzinfo=utc), verbose_name='date of creation'),
        ),
    ]
