# Generated by Django 2.1.15 on 2020-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_help_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, help_text='Add your street and number for exact location (leave it out if you feel uncomfortable with it);max length 500 characters', max_length=500),
        ),
    ]
