# Generated by Django 3.0.3 on 2020-03-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200313_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.CharField(blank=True, default='13.03.2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registered_on',
            field=models.DateField(blank=True, default='13.03.2020', max_length=100),
        ),
    ]
