# Generated by Django 2.1.5 on 2020-04-10 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200410_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slogan',
            field=models.CharField(blank=True, help_text='The headline of your post (will be shown on map)', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9, !.?]*$', 'allowed are characters, numbers, points, question and exclamation mark')]),
        ),
    ]
