# Generated by Django 3.0.3 on 2020-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200313_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
