# Generated by Django 3.0.3 on 2020-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200313_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='help_type',
            field=models.CharField(choices=[(0, 'Food'), (1, 'Medical Aid'), (2, 'Online-Teaching of Students'), (3, 'Child Care')], default=1, max_length=1),
        ),
    ]
