# Generated by Django 2.1.5 on 2020-04-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200411_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slogan',
        ),
    ]
