# Generated by Django 2.2.11 on 2020-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_help_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_membership',
            field=models.CharField(choices=[('0', 'helper'), ('1', 'taker')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='help_type',
            field=models.CharField(choices=[('0', 'Food'), ('1', 'Medical Aid'), ('2', 'Online-Teaching of Students'), ('3', 'Child Care')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, default=52, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, default=42, null=True),
        ),
    ]
