# Generated by Django 3.0.4 on 2020-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200320_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='help_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registered_on',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tel_mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tel_private',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='web',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_membership',
            field=models.CharField(choices=[('0', 'I want to help'), ('1', 'I need help')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
