# Generated by Django 2.1.5 on 2020-04-11 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, help_text='The detailed description of your post (will be shown on map)', max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9, !.?]*$', 'allowed are characters, numbers, points, question and exclamation mark')]),
        ),
    ]
