# Generated by Django 3.0.4 on 2020-03-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200321_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='map_show_location',
            field=models.CharField(choices=[('0', 'rough'), ('1', 'exact')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_membership',
            field=models.CharField(choices=[('0', 'I want to help'), ('1', 'I need help'), ('2', 'Inactive (no point shown in map)')], default=2, max_length=1),
        ),
    ]
