# Generated by Django 2.1.15 on 2020-04-12 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200411_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_Main_Img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, help_text='The detailed description of your post (will be shown on map)', max_length=255, null=True),
        ),
    ]
