# Generated by Django 3.0.3 on 2020-03-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200325_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_membership',
            field=models.CharField(choices=[('0', 'I want to help'), ('1', 'I need help'), ('2', 'Inactive (invisible to others)')], default=2, max_length=1),
        ),
    ]
