# Generated by Django 2.1.15 on 2020-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200412_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userImg_Url',
            field=models.CharField(blank=True, default=0, max_length=500),
        ),
    ]
