# Generated by Django 2.1.15 on 2020-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_userimg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_Main_Img',
            field=models.ImageField(blank=True, default=0, upload_to='images/'),
        ),
    ]
