# Generated by Django 2.1.5 on 2020-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200413_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_Main_Img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
