# Generated by Django 2.1.5 on 2020-04-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200416_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_membership',
            field=models.CharField(choices=[('0', 'offer help'), ('1', 'find help'), ('2', 'find help anonymously'), ('3', 'present a shop')], default=2, max_length=1),
        ),
    ]
