# Generated by Django 2.1.5 on 2020-04-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200416_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop_type',
        ),
    ]
