# Generated by Django 2.1.5 on 2020-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_customuser_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('0', 'Grocery Store'), ('1', 'Pharmacy'), ('2', 'Other Store')], max_length=255),
        ),
    ]
