# Generated by Django 2.1.5 on 2020-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='help_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
