# Generated by Django 2.1.5 on 2020-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200416_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_deliver',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_open',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_pickup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
