# Generated by Django 2.1.15 on 2020-04-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200416_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery Store'), ('Pharmacy', 'Pharmacy'), ('Other', 'Other Store')], max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_Main_Img',
            field=models.ImageField(blank=True, default=0, upload_to='images/'),
        ),
    ]
